class Hotjobs {
  final String title;
  final String description;
  final String artwork;
  final String imageUrl;
  final String expdate;
  final String jobref;
  final String jdposition;
  final String jblocation;
  final String jbtechnology;
  final String jbsalary;
  final String jbexp;
  final List<String> tag;
  final List<String> jobResponsbilities;

  Hotjobs({
    required this.title,
    required this.description,
    required this.artwork,
    required this.imageUrl,
    required this.expdate,
    required this.jobref,
    required this.jdposition,
    required this.jblocation,
    required this.jbtechnology,
    required this.jbsalary,
    required this.jbexp,
    required this.tag,
    required this.jobResponsbilities,
  });
}

List<Hotjobs> hotjobList = [
  Hotjobs(
    title: "GENESIIS",
    description: "SSE - Full Stack",
    expdate: 'Sun Dec 02 2023',
    artwork: 'http://www.topjobs.lk/logo/0000000001/2590cf.jpg',
    imageUrl: 'assets/company/genesiis.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Dialog",
    description: "Senior Executive - Financial",
    expdate: 'Sun Dec 02 2023',
    artwork: 'http://www.topjobs.lk/logo/DEFZZZ/1022c9hx.png',
    imageUrl: 'assets/company/dialog.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "WSO2",
    description: "QA Engineer",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/wso2.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Virtusa",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/virtusa.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Sysco Labs",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/syscolabs.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "ISM",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/ism.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "MIT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/mit.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "SLT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/slt.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "GENESIIS",
    description: "SSE - Full Stack",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/genesiis.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Dialog",
    description: "Senior Executive - Financial",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/dialog.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "WSO2",
    description: "QA Engineer",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/wso2.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Virtusa",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/virtusa.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Sysco Labs",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/syscolabs.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "ISM",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/ism.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "MIT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/mit.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "SLT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/slt.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "GENESIIS",
    description: "SSE - Full Stack",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/genesiis.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Dialog",
    description: "Senior Executive - Financial",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/dialog.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "WSO2",
    description: "QA Engineer",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/wso2.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Virtusa",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/virtusa.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Sysco Labs",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/syscolabs.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "ISM",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/ism.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "MIT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/mit.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "SLT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/slt.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "GENESIIS",
    description: "SSE - Full Stack",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/genesiis.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Dialog",
    description: "Senior Executive - Financial",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/dialog.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "WSO2",
    description: "QA Engineer",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/wso2.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Virtusa",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/virtusa.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Sysco Labs",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/syscolabs.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "ISM",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/ism.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "MIT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/mit.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "SLT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/slt.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "GENESIIS",
    description: "SSE - Full Stack",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/genesiis.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Dialog",
    description: "Senior Executive - Financial",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/dialog.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "WSO2",
    description: "QA Engineer",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/wso2.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Virtusa",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/virtusa.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Sysco Labs",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/syscolabs.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "ISM",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/ism.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "MIT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/mit.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "SLT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/slt.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  ),
  Hotjobs(
    title: "Airtel",
    description: "Marketing Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/airtel.png',
    jobref: '1098607',
    jdposition: 'Full Time',
    jblocation: 'Colombo 4, Sri Lanka',
    jbtechnology: 'Angular/React/Java',
    jbsalary: 'N/A',
    jbexp: '3-5 Years',
    tag: [
      "Full Time",
      "Remote",
      "Anywhere",
    ],
    jobResponsbilities: [
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
      "Calendly is looking for a UI/UX Designer in Marketing to Join our fast growing team. This role will report to the Director of UX and work alongside the marketing team to design experiences that help grow our business.",
    ],
  )
];
