class Hotjobs {
  String title;
  String description;
  String artwork;
  String imageUrl;
  String expdate;
  String jobref;
  String jdposition;
  String jblocation;
  String jbtechnology;
  String jbsalary;
  String jbexp;

  Hotjobs({
    required this.title,
    required this.description,
    required this.artwork,
    required this.imageUrl,
    required this.expdate,
    required this.jobref,
    required this.jdposition,
    required this.jblocation,
    required this.jbtechnology,
    required this.jbsalary,
    required this.jbexp,
  });

  static List<Hotjobs> hotjobList = [
    Hotjobs(
      title: "GENESIIS",
      description: "SSE - Full Stack",
      expdate: 'Sun Dec 02 2023',
      artwork: 'http://www.topjobs.lk/logo/0000000001/2590cf.jpg',
      imageUrl: 'assets/company/genesiis.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Dialog",
      description: "Senior Executive - Financial Accounting",
      expdate: 'Sun Dec 02 2023',
      artwork: 'http://www.topjobs.lk/logo/DEFZZZ/1022c9hx.png',
      imageUrl: 'assets/company/dialog.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "WSO2",
      description: "QA Engineer",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/wso2.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Virtusa",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/virtusa.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Sysco Labs",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/syscolabs.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "ISM",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/ism.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "MIT",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/mit.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "SLT",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/slt.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "GENESIIS",
      description: "SSE - Full Stack",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/genesiis.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Dialog",
      description: "Senior Executive - Financial Accounting",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/dialog.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "WSO2",
      description: "QA Engineer",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/wso2.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Virtusa",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/virtusa.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Sysco Labs",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/syscolabs.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "ISM",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/ism.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "MIT",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/mit.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "SLT",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/slt.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "GENESIIS",
      description: "SSE - Full Stack",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/genesiis.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Dialog",
      description: "Senior Executive - Financial Accounting",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/dialog.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "WSO2",
      description: "QA Engineer",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/wso2.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Virtusa",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/virtusa.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Sysco Labs",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/syscolabs.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "ISM",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/ism.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "MIT",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/mit.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "SLT",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/slt.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "GENESIIS",
      description: "SSE - Full Stack",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/genesiis.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Dialog",
      description: "Senior Executive - Financial Accounting",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/dialog.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "WSO2",
      description: "QA Engineer",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/wso2.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Virtusa",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/virtusa.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Sysco Labs",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/syscolabs.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "ISM",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/ism.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "MIT",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/mit.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "SLT",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/slt.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "GENESIIS",
      description: "SSE - Full Stack",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/genesiis.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Dialog",
      description: "Senior Executive - Financial Accounting",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/dialog.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "WSO2",
      description: "QA Engineer",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/wso2.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Virtusa",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/virtusa.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Sysco Labs",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/syscolabs.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "ISM",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/ism.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "MIT",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/mit.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "SLT",
      description: "Project Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/slt.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    ),
    Hotjobs(
      title: "Airtel",
      description: "Marketing Manager",
      expdate: 'Sun Dec 02 2023',
      artwork: 'https://iili.io/HPgJmgt.md.png',
      imageUrl: 'assets/company/airtel.png',
      jobref: '1098607',
      jdposition: 'Full Time',
      jblocation: 'Colombo 4, Sri Lanka',
      jbtechnology: 'Angular/React/Java',
      jbsalary: 'N/A',
      jbexp: '3-5 Years',
    )
  ];
}
