class Hotjobs {
  String title;
  String description;
  String artwork;
  String imageUrl;
  String expdate;

  Hotjobs({
    required this.title,
    required this.description,
    required this.artwork,
    required this.imageUrl,
    required this.expdate,
  });
}

List<Hotjobs> hotjobList = [
  Hotjobs(
    title: "GENESIIS",
    description: "Senior Software Engineer - Full Stack",
    expdate: 'Sun Dec 02 2023',
    artwork: 'http://www.topjobs.lk/logo/0000000001/2590cf.jpg',
    imageUrl: 'assets/company/genesiis.png',
  ),
  Hotjobs(
    title: "Dialog",
    description: "Senior Executive - Financial Accounting and Reporting",
    expdate: 'Sun Dec 02 2023',
    artwork: 'http://www.topjobs.lk/logo/DEFZZZ/1022c9hx.png',
    imageUrl: 'assets/company/dialog.png',
  ),
  Hotjobs(
    title: "WSO2",
    description: "QA Engineer",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/wso2.png',
  ),
  Hotjobs(
    title: "Virtusa",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/virtusa.png',
  ),
  Hotjobs(
    title: "Sysco Labs",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/syscolabs.png',
  ),
  Hotjobs(
    title: "ISM",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/ism.png',
  ),
  Hotjobs(
    title: "MIT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/mit.png',
  ),
  Hotjobs(
    title: "SLT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/slt.png',
  ),
  Hotjobs(
    title: "GENESIIS",
    description: "Senior Software Engineer - Full Stack",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/genesiis.png',
  ),
  Hotjobs(
    title: "Dialog",
    description: "Senior Executive - Financial Accounting and Reporting",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/dialog.png',
  ),
  Hotjobs(
    title: "WSO2",
    description: "QA Engineer",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/wso2.png',
  ),
  Hotjobs(
    title: "Virtusa",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/virtusa.png',
  ),
  Hotjobs(
    title: "Sysco Labs",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/syscolabs.png',
  ),
  Hotjobs(
    title: "ISM",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/ism.png',
  ),
  Hotjobs(
    title: "MIT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/mit.png',
  ),
  Hotjobs(
    title: "SLT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/slt.png',
  ),
  Hotjobs(
    title: "GENESIIS",
    description: "Senior Software Engineer - Full Stack",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/genesiis.png',
  ),
  Hotjobs(
    title: "Dialog",
    description: "Senior Executive - Financial Accounting and Reporting",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/dialog.png',
  ),
  Hotjobs(
    title: "WSO2",
    description: "QA Engineer",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/wso2.png',
  ),
  Hotjobs(
    title: "Virtusa",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/virtusa.png',
  ),
  Hotjobs(
    title: "Sysco Labs",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/syscolabs.png',
  ),
  Hotjobs(
    title: "ISM",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/ism.png',
  ),
  Hotjobs(
    title: "MIT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/mit.png',
  ),
  Hotjobs(
    title: "SLT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/slt.png',
  ),
  Hotjobs(
    title: "GENESIIS",
    description: "Senior Software Engineer - Full Stack",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/genesiis.png',
  ),
  Hotjobs(
    title: "Dialog",
    description: "Senior Executive - Financial Accounting and Reporting",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/dialog.png',
  ),
  Hotjobs(
    title: "WSO2",
    description: "QA Engineer",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/wso2.png',
  ),
  Hotjobs(
    title: "Virtusa",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/virtusa.png',
  ),
  Hotjobs(
    title: "Sysco Labs",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/syscolabs.png',
  ),
  Hotjobs(
    title: "ISM",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/ism.png',
  ),
  Hotjobs(
    title: "MIT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/mit.png',
  ),
  Hotjobs(
    title: "SLT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/slt.png',
  ),
  Hotjobs(
    title: "GENESIIS",
    description: "Senior Software Engineer - Full Stack",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/genesiis.png',
  ),
  Hotjobs(
    title: "Dialog",
    description: "Senior Executive - Financial Accounting and Reporting",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/dialog.png',
  ),
  Hotjobs(
    title: "WSO2",
    description: "QA Engineer",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/wso2.png',
  ),
  Hotjobs(
    title: "Virtusa",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/virtusa.png',
  ),
  Hotjobs(
    title: "Sysco Labs",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/syscolabs.png',
  ),
  Hotjobs(
    title: "ISM",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/ism.png',
  ),
  Hotjobs(
    title: "MIT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/mit.png',
  ),
  Hotjobs(
    title: "SLT",
    description: "Project Manager",
    expdate: 'Sun Dec 02 2023',
    artwork: 'https://iili.io/HPgJmgt.md.png',
    imageUrl: 'assets/company/slt.png',
  )
];
